### ISSUE TITLE
go-l10n/examples/web/ fails at runtime

### ISSUE THREAD

**Issue by joeblew99** [iafan/go-l10n#2]
Its looking for the templates and panicing out.

"open templates/hello.html: no such file or directory"

````
make ln-web-run
cd /Users/apple/workspace/go/src/github.com/iafan/go-l10n/examples/web && go build -o /Users/apple/workspace/go/src/bitbucket.org/gedw99/centri/client/i18n/bin/web *.go
/Users/apple/workspace/go/src/bitbucket.org/gedw99/centri/client/i18n/bin/web
2019/04/22 19:34:18 http: panic serving [::1]:49586: open templates/hello.html: no such file or directory
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc000128000)
        /usr/local/opt/go/libexec/src/net/http/server.go:1769 +0x139
panic(0x1398040, 0xc00011fec0)
        /usr/local/opt/go/libexec/src/runtime/panic.go:522 +0x1b5
main.indexPage(0x1483140, 0xc00015c000, 0xc00014e000)
        /Users/apple/workspace/go/src/github.com/iafan/go-l10n/examples/web/main.go:22 +0x411
net/http.HandlerFunc.ServeHTTP(0x1417500, 0x1483140, 0xc00015c000, 0xc00014e000)
        /usr/local/opt/go/libexec/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x172a880, 0x1483140, 0xc00015c000, 0xc00014e000)
        /usr/local/opt/go/libexec/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0000ac8f0, 0x1483140, 0xc00015c000, 0xc00014e000)
        /usr/local/opt/go/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000128000, 0x14838c0, 0xc00011c100)
        /usr/local/opt/go/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/opt/go/libexec/src/net/http/server.go:2884 +0x2f4
2019/04/22 19:34:18 http: panic serving [::1]:49587: open templates/hello.html: no such file or directory
goroutine 19 [running]:
net/http.(*conn).serve.func1(0xc000092fa0)
        /usr/local/opt/go/libexec/src/net/http/server.go:1769 +0x139
panic(0x1398040, 0xc000077da0)
        /usr/local/opt/go/libexec/src/runtime/panic.go:522 +0x1b5
main.indexPage(0x1483140, 0xc000194000, 0xc000112100)
        /Users/apple/workspace/go/src/github.com/iafan/go-l10n/examples/web/main.go:22 +0x411
net/http.HandlerFunc.ServeHTTP(0x1417500, 0x1483140, 0xc000194000, 0xc000112100)
        /usr/local/opt/go/libexec/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x172a880, 0x1483140, 0xc000194000, 0xc000112100)
        /usr/local/opt/go/libexec/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0000ac8f0, 0x1483140, 0xc000194000, 0xc000112100)
        /usr/local/opt/go/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000092fa0, 0x14838c0, 0xc00008a3c0)
        /usr/local/opt/go/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/opt/go/libexec/src/net/http/server.go:2884 +0x2f4
2019/04/22 19:34:18 http: panic serving [::1]:49588: open templates/hello.html: no such file or directory
goroutine 36 [running]:
net/http.(*conn).serve.func1(0xc0001280a0)
        /usr/local/opt/go/libexec/src/net/http/server.go:1769 +0x139
panic(0x1398040, 0xc000077dd0)
        /usr/local/opt/go/libexec/src/runtime/panic.go:522 +0x1b5
main.indexPage(0x1483140, 0xc0001dc000, 0xc0001cc000)
        /Users/apple/workspace/go/src/github.com/iafan/go-l10n/examples/web/main.go:22 +0x411
net/http.HandlerFunc.ServeHTTP(0x1417500, 0x1483140, 0xc0001dc000, 0xc0001cc000)
        /usr/local/opt/go/libexec/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x172a880, 0x1483140, 0xc0001dc000, 0xc0001cc000)
        /usr/local/opt/go/libexec/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0000ac8f0, 0x1483140, 0xc0001dc000, 0xc0001cc000)
        /usr/local/opt/go/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0001280a0, 0x14838c0, 0xc0001c6040)
        /usr/local/opt/go/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/opt/go/libexec/src/net/http/server.go:2884 +0x2f4
2019/04/22 19:34:21 http: panic serving [::1]:49606: open templates/hello.html: no such file or directory
goroutine 5 [running]:
net/http.(*conn).serve.func1(0xc000204000)
        /usr/local/opt/go/libexec/src/net/http/server.go:1769 +0x139
panic(0x1398040, 0xc000216de0)
        /usr/local/opt/go/libexec/src/runtime/panic.go:522 +0x1b5
main.indexPage(0x1483140, 0xc000210000, 0xc000112200)
        /Users/apple/workspace/go/src/github.com/iafan/go-l10n/examples/web/main.go:22 +0x411
net/http.HandlerFunc.ServeHTTP(0x1417500, 0x1483140, 0xc000210000, 0xc000112200)
        /usr/local/opt/go/libexec/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x172a880, 0x1483140, 0xc000210000, 0xc000112200)
        /usr/local/opt/go/libexec/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0000ac8f0, 0x1483140, 0xc000210000, 0xc000112200)
        /usr/local/opt/go/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000204000, 0x14838c0, 0xc00008a580)
        /usr/local/opt/go/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/opt/go/libexec/src/net/http/server.go:2884 +0x2f4
2019/04/22 19:34:21 http: panic serving [::1]:49607: open templates/hello.html: no such file or directory
goroutine 20 [running]:
net/http.(*conn).serve.func1(0xc000093040)
        /usr/local/opt/go/libexec/src/net/http/server.go:1769 +0x139
panic(0x1398040, 0xc0001c5d70)
        /usr/local/opt/go/libexec/src/runtime/panic.go:522 +0x1b5
main.indexPage(0x1483140, 0xc0002100e0, 0xc0001cc100)
        /Users/apple/workspace/go/src/github.com/iafan/go-l10n/examples/web/main.go:22 +0x411
net/http.HandlerFunc.ServeHTTP(0x1417500, 0x1483140, 0xc0002100e0, 0xc0001cc100)
        /usr/local/opt/go/libexec/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x172a880, 0x1483140, 0xc0002100e0, 0xc0001cc100)
        /usr/local/opt/go/libexec/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0000ac8f0, 0x1483140, 0xc0002100e0, 0xc0001cc100)
        /usr/local/opt/go/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000093040, 0x14838c0, 0xc0001c6200)
        /usr/local/opt/go/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/opt/go/libexec/src/net/http/server.go:2884 +0x2f4
2019/04/22 19:34:21 http: panic serving [::1]:49608: open templates/hello.html: no such file or directory
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc0002040a0)
        /usr/local/opt/go/libexec/src/net/http/server.go:1769 +0x139
panic(0x1398040, 0xc0002466f0)
        /usr/local/opt/go/libexec/src/runtime/panic.go:522 +0x1b5
main.indexPage(0x1483140, 0xc0002101c0, 0xc000112300)
        /Users/apple/workspace/go/src/github.com/iafan/go-l10n/examples/web/main.go:22 +0x411
net/http.HandlerFunc.ServeHTTP(0x1417500, 0x1483140, 0xc0002101c0, 0xc000112300)
        /usr/local/opt/go/libexec/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x172a880, 0x1483140, 0xc0002101c0, 0xc000112300)
        /usr/local/opt/go/libexec/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc0000ac8f0, 0x1483140, 0xc0002101c0, 0xc000112300)
        /usr/local/opt/go/libexec/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0002040a0, 0x14838c0, 0xc00008a8c0)
        /usr/local/opt/go/libexec/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
        /usr/local/opt/go/libexec/src/net/http/server.go:2884 +0x2f4
````

**Comment by iafan** [comment]
I think the compiled binary expects the https://github.com/iafan/go-l10n/blob/master/examples/web/templates/hello.html file to be under `templates/hello.html` path relative to the binary. In your case that would be `/Users/apple/workspace/go/src/bitbucket.org/gedw99/centri/client/i18n/bin/web/templates/hello.html`

**Comment by iafan** [comment]
Closing the old issue; let me know if the problem persists even after the template files are copied to the correct location.
